### ISSUE TITLE
Uso de Bonificaciones

### ISSUE THREAD

**Issue by sierraja** [wnpower/iFactura-API-Integracion#10]
Buenos días. Estamos precisando utilizar descuestos generales sobre el monto total de cada factura enviada y quisieramos saber como se aplica. Gracias por su atención

**Comment by villaboamiguel** [comment]
Hola!
Las bonificaciones podes mostrarlas como un porcentaje dentro de la linea del producto vendido. Una bonificación del 20% sobre ese item. El campo Bonificación en la API te permite informar un % en formato Double con 2 decimales. Entre 0% y 99%.
Este porcentaje de descuento será calculado en base al valor definido en la propiedad Total.

O enviar directamente el valor con el descuento o bonificación aplicada.
Saludos
