### ISSUE TITLE
Error de fecha

### ISSUE THREAD

**Issue by sramallo** [wnpower/iFactura-API-Integracion#12]
Hola buenas tardes
Esta tarde logré conectarme con la API por primera vez!!! todo un logo :):):)

Me está dando este error:

La fecha del comprobante no puede ser anterior a la fecha del ultimo comprobante emitido. Comprobante 0001 - 00000070 (07/12/2021)

Sin embargo en el visor de eventos veo que dió de alta la factura

Quería consultar el motivo posible que me dé este error.

Lo que envié fue la factura de ejemplo json que está publicada, solo le puse fecha del 20211201 y el número de factura era 20.

Tampoco sé porque me dice que el comprobante es el número 70.

Desde ya muchas gracias
Saludos cordiales
Susana

**Comment by villaboamiguel** [comment]
Hola!
Estas utilizando el entorno demo de iFactura? Ese entorno es utilizado como sandbox por otros usuarios también y por ende puede haber otro comprobante emitido previo al tuyo y ese sea el ultimo emitido. En caso que mencionás se ve que existe el comprobante que termina 70 para el punto de venta 1 con fecha del día 07/12 y por control no se puede emitir un comprobante anterior al ultimo emitido en lo que respecta a fechas.

El número de comprobante por más que lo especifiques en la API, va a ser asignado por AFIP al momento de emisión. El completar dicho campo es opcional y es para obtener cierto control y seguimiento en los eventos del sistema si queres buscar alguna emisión con dicho código.

En este caso si cambiás la fecha de comprobante al 8/12/2021, el número de comprobante probablemente sea el 71 para el punto de venta 1. 

Saludos

**Comment by sramallo** [comment]
Ok, perfecto si, ese es el caso estoy usando el entorno de demo de iFactura.

Quería consultarte si hay documentación sobre las validaciones que hace la API como para ver si me falta alguna, por ejemplo los campos que son obligatorios estoy controlando en mi sistema que no falten, el CUIT ya sé que ve correcto porque lo valido, hay otras validaciones a tener en cuenta? 

Acabo de hacer una factura exitosa, le mandé fecha 08-12 en las 4 fechas, me asignó el número 71 y lo puedo ver en el visor de eventos.

Como puedo obtener ese número 71 que me asignó?

Otra consulta cuando accedo a https://app.ifactura.com.ar/Factura/ImprimirExterno/{hash} con el hash que devuelve la petición me muestra una factura del 2015 con un valor distinto al que yo le envié, forma parte del entorno de prueba? 


Muchas gracias
Saludos
Susana

**Comment by villaboamiguel** [comment]
Hola!
Por lo que son validaciones, tenes para todos los campos obligatorios que tengan algún tipo de sentido. Por ejemplo que si específicas un CUIT, sea de tipo CUIT y todos los datos del cliente estén completados. O que los totales y los impuestos den correctamente.

El número de comprobante no lo devuelve la API en su respuesta de estar correctamente emitido. Solo el hash para que puedas ubicar el comprobante en iFactura.

El hash si lo emitiste con el entorno demo deberías apuntar a https://demo.ifactura.com.ar/Factura/ImprimirExterno/{hash} si apuntás a producción debes ir a https://app.ifactura.com.ar/Factura/ImprimirExterno/{hash}. Los hashes generados en el entorno demo pueden ser facturas al azar en el entorno de producción por como se generan los hashes.

Saludos!

**Comment by sramallo** [comment]
ok, perfecto

y hay alguna forma de relacionar una factura emitida por ifactura con los datos que guardamos en el sistema?
Por ejemplo, si le mando a ifactura el número interno que yo tengo, en un campo por ejemplo Leyenda, como para que el usuario pueda relacionar el pago que le hacen con algún número que salga en la factura?

Muchas gracias
Susana

**Comment by villaboamiguel** [comment]
Si eso es correcto. O en el detalle de la factura podes mandar lo que quieras dentro del campo "Descripción" o "Código".
Por ejemplo, utilizando el campo "Descripción" de un detalle facturado podes poner "según orden 1259988". O esto mismo en la leyenda de cada comprobante. A gusto de como lo quieras hacer.

Saludos!

**Comment by sramallo** [comment]
En la leyenda sería mejor, porque en las lineas de detalle tal vez se pierda, ellos usan números de serie de los productos.

En que parte de la factura sale la Leyenda?

Susana

**Comment by villaboamiguel** [comment]
Hola! en la sección de personalización de iFactura podes ver como quedan con valores de ejemplo cada campo (https://demo.ifactura.com.ar/Facturacion/CargarLogo). Te adjunto un PDF recién generado con ello. La leyenda la vas a ver donde dice "Leyenda Demo". Así y todo podes utilizar este entorno demo para mandar leyendas e ir probando,

Saludos
[VerEjemploComprobante.pdf](https://github.com/wnpower/iFactura-API-Integracion/files/7685903/VerEjemploComprobante.pdf)

**Comment by sramallo** [comment]
Ok, muchisimas gracias!!

**Comment by sramallo** [comment]
Hola buenas tardes

Tengo otra consulta, este cliente vende productos con números de serie.

Las facturas se confeccionan agregando los números de serie en los renglones que siguen al producto.

Por ejemplo se factura el producto xxxx con codigo 01-002, su importe unitario, cantidad e importe total.
En el renglón siguiente se muestra sin código de producto, con cantidad en 1, en descripción los números de serie, en importe unitario y total van 0.

Cómo podría replicar este comportamiento en la factura electrónica?

Me dice Valor unitario inválido si le pongo 0.

Probé las combinaciones que se ocurrieron, cantidad 0, tipo producto servicio, pero me sigue dando error.

Cómo se acostumbra a agregar una linea de detalle sin producto como este caso?

Desde ya muchas gracias
Susana

**Comment by villaboamiguel** [comment]
Hola!

Claro, detalles con valor 0 no acepta iFactura dado que el servicio web no soporta el valor 0 en estos detalles que se le comunican. Lo que podes hacer es enviar todo lo que quieras informar en el detalle que si tiene valor y probar como se ve en la demo de iFactura.

Saludos.

**Comment by sramallo** [comment]
Y si le pongo valor 0.01?
Técnicamente funciona, ya hice la prueba.

Me falta la autorización del contador porque cambiará el valor de la factura.

Tenés noticia de otras personas que hayan hecho eso?

Gracias
Susana

**Comment by villaboamiguel** [comment]
No tengo en mente, ni en los issues de este repositorio alguno que lo haya hecho así con iFactura.

**Comment by sramallo** [comment]
Hola buen día
Ya armé la linea de detalle como para que contenga los números de serie, muchas gracias por la ayuda.

Tengo otra consulta que no es tan técnica, no sé si amerita levantar un ticket.

La consulta es que necesito saber cual va a ser el punto de venta que corresponde a la empresa para la factura electrónica.
Lo necesitamos conocer ahora antes de implementar porque para hacer los remitos con la imprenta hay que hacerlos con este nuevo punto de venta.

Sabés como se puede averiguarlo? Porque el contador de la empresa me dijo que se hace al habilitar en el web service.

Desde ya muchas gracias
Susana

**Comment by villaboamiguel** [comment]
Hola,
El punto de venta lo definís cuando enviás el pedido a iFactura para facturar.
Si te referís a como en AFIP verificás cual es tu punto de venta para factura electrónica, tenés la guia de alta de iFactura que te dice como se crea el mismo: https://help.wnpower.com/hc/es/articles/360018269432-Configuraci%C3%B3n-Inicial-de-iFactura

Saludos

**Comment by sramallo** [comment]
Hola buen dia

Muchas gracias por la info

Quería consultarte por el campo AutoEnvioCorreo, en las pruebas le puse true y al cliente le puse mi dirección de mail para probar como funciona pero no recibí el mail.

Es porque en ambiente de prueba n está funcionando o me faltó hacer algo?

Saludos y gracias
Susana

**Comment by villaboamiguel** [comment]
Hola Susana,

La versión demo no envia realmente los correos para evitar que los servicios de iFactura sean catalogados como SPAM.

Saludos

**Comment by sramallo** [comment]
Hola buenos días, feliz año!!!

Tengo una consulta respecto del monto para poder facturar Consumidor Final sin declarar el cliente, sigue siendo de 5000 o se actualizó?

Muchas gracias
Susana

**Comment by villaboamiguel** [comment]
Hola!

Si, sigue siendo de $ 5000 para los casos de Factura B con consumidor final. Cuando se actualice dicho valor será actualizada la documentación de la API.

Saludos

**Comment by sramallo** [comment]
ok, muchas gracias!!!
Saludos

**Comment by sramallo** [comment]
Hola buenos dias
Estamos viendo la posibilidad de usar la API en otro cliente, este cliente utiliza Factura de Crédito Electrónica.

Se puede implementar con iFactura?
Suelen hacer 1 ó 2 facturas de este tipo por mes, pero necesitamos saber si esto es posible y como se implementa.

Por supuesto que tambien Notas de Crédito del mismo tipo.

Desde ya muchas gracias
Susana

**Comment by villaboamiguel** [comment]
Hola,
Por el momento iFactura no es compatible con la emisión de facturas de crédito electrónicas.
Solo comprobantes A, B y C que están descriptos en la documentación de este repositorio.
Saludos

**Comment by sramallo** [comment]
ok, muchas gracias

Otra consulta, en caso de clientes que no se identifican porque el importe es menor a 5000, si se da el caso que está caido el sitio o pasa algún inconveniente que el comprobante queda sin CAE porque el sistema no puede conectarse momentaneamente con la API, que opciones se acostumbra a usar para darle un comprobante a esa persona?

El sistema que emite los comprobantes y que se conecta con la API tiene guardada la información y le podría imprimir el comprobante, pero no es válido.
Mi pregunta apunta a cuales son las estrategias que suelen usarse.

Porque si el cliente está registrado tenemos el mail y se lo mandamos más tarde, pero no sé como sería en clientes que están de paso.

Muchas gracias
Susana

**Comment by fedealvz** [comment]
Hola @sramallo !

Para factura electrónica, la reglamentación [RG 2485](http://biblioteca.afip.gob.ar/dcp/reag01002485_2008_08_28) en su Art. 29 describe estos casos.

Generalmente se pide un e-mail a donde luego se la enviarás. Sin embargo, es algo que dependiendo de tu actividad y relación con el cliente, deberás acordar en el momento con él.

PD: Recordá por favor abrir un nuevo "Issue" para cada pregunta de diferente tema que tengas, así luego es fácil para los demás usuarios poder encontrar los diferentes temas.

Saludos!
