### ISSUE TITLE
Respuesta de error

### ISSUE THREAD

**Issue by jfgancia** [wnpower/iFactura-API-Integracion#14]
Hola estimados, no entiendo donde tengo el problema en mi conexión a su api.
Estoy trabajando con PHP nativo y he utilizado de base el ejemplo de php de su api.

Mensaje: {"Exito":false,"Mensaje":"El detalle de facturación es requerido"}

Subo 2 capturas, si imprimo el array se ve completo.

// borro fotos por mostrar info comprometida.

Desde ya, gracias!

Saludos,

**Comment by villaboamiguel** [comment]
Hola!

Proba haciendo que $i sea igual a 0 para que el objeto detalle este primero en el array de detalles.

Saludos.

**Comment by jfgancia** [comment]
> Hola!
> 
> Proba haciendo que $i sea igual a 0 para que el objeto detalle este primero en el array de detalles.
> 
> Saludos.

Funciono, gracias!
