### ISSUE TITLE
Consulta API

### ISSUE THREAD

**Issue by dktcoding** [wnpower/iFactura-API-Integracion#2]
Hola, tenía 2 consultas (asumiendo iFactura correctamente configurado):

- ¿Hay forma de probar que el POST es correcto sin facturar? es decir, probar que el POST es correcto, pero sin emitir una factura.
- ¿Hay forma de hacer una consulta sobre el Padrón A5 desde la API? se que puede hacerse desde la aplicación web, pero sería interesante poder hacerlo desde la API.

Saludos

**Comment by WNPowerStaff** [comment]
Hola @dktcoding te respondo:

1. Podés usar el sandbox (testing) para hacer todas las pruebas necesarias e incluso generar comprobantes sin valor fiscal. Una vez que dejaste todo listo, cambiás el sandbox por producción y listo. Para obtener un usuario de sandbox podés cargar un ticket en tu panel de autogestión.

2. Actualmente no está disponible vía API, pero podés proponer nuevas funciones en nuestro foro de comunidad: https://help.wnpower.com/hc/es/community/topics

Saludos y feliz año!

**Comment by dktcoding** [comment]
Genial!

Y en caso de que a alguien mas le interese pueden votar por la nueva función en: https://help.wnpower.com/hc/es/community/posts/360037137991-Acceso-a-Padrón-A5-v%C3%ADa-API-iFactura

Saludos
