### ISSUE TITLE
Problema con la traducción en el front end, en la página de "Finalizar compra"

### ISSUE THREAD

**Issue by MaritoCe** [wnpower/iFactura-API-Integracion#3]
Hola! Tengo instalado el plugin de iFactura en mi sitio web con Woocommerce, pero necesito resolver un inconveniente. Como se ve en la foto que adjunto, por alguna razón no está tomando la traducción de las cadenas de texto en la página "Finalizar compra". Revisé los archivos de traducción .po y las traducciones están ahí, pero no se por qué no las toma. 

Habrá algún error en el código del plugin, en la instrucción de esos campos, que no las traduce?

Muchas gracias por su respuesta.
Saludos!
![Anotación 2020-06-25 094649](https://user-images.githubusercontent.com/24298321/85723605-c8193b80-b6c9-11ea-9b9a-af84a7c991ab.jpg)

**Comment by fedealvz** [comment]
Hola Marito! Te sugiero que abras un issue en el repo oficial del plugin de iFactura-WooCommerce en https://github.com/fedealvz/Woo-iFactura

**Comment by MaritoCe** [comment]
Ok gracias!
