### ISSUE TITLE
Testing Demo con type response = opaque y estatus=200

### ISSUE THREAD

**Issue by sierraja** [wnpower/iFactura-API-Integracion#4]
Buenos días, estoy tratando de hacer las pruebas de la API contra la plataforma de prueba con el usuario demo@ifactura.com.ar. Estoy haciendo las peticiones desde nuestro dominio, a través de una interfaz web y utilizando una funcion de javascript con el siguiente codigo:

`var urlEmitirFacturaDemo='https://demo.ifactura.com.ar/API/EmitirFactura';
      fetch(urlEmitirFacturaDemo, {
        method: 'POST',
        mode: 'no-cors',
        body: JSON.stringify(jsonObject),
        headers:{'content-type': 'application/json'}
      })
        .then(response => {
          console.log(response);
        })
        .catch(err => {
          console.error(err);
        });`

Como mencione en el título, la respuesta es una cadena vacía, sin mensaje de error y con estatus 200 en ok, no logro obtener el estados, el mensaje y el id de la factura. 

He cumplido con los requisitos, según documentación.

Estoy a la espera de alguna sugerencia o consulta acerca del tema para su mejor compresión. Gracias por su tiempo y dedicación.

**Comment by villaboamiguel** [comment]
Hola!

La API de iFactura esta diseñada para la que utilices desde el lado del servidor de tu aplicación (backend), si lo haces desde la interfaz web directamente a iFactura te va afectar la protección de CORS de los navegadores.

Si tu sistema (backend) esta hecho, por ejemplo en PHP, podes implementar la API ahí como indican los ejemplos y después desde el frontend de tu aplicación llamar a dicha implementación en tu servidor.

Como ejemplo si te sirve esta el plugin no oficial de Woocommerce para iFactura que tiene en PHP la implementación de la API de iFactura y desde Woocommerce se llama mediante JS a esta implementación mediante un GET.
https://github.com/fedealvz/Woo-iFactura

Saludos!

**Comment by sierraja** [comment]
ok, hicimos algunos cambios atendiendo tu sugerencia.

Estoy enviando la peticion desde al backend con php y muestro los resultados en mi frontend con una funcion y finalmente  podemos ver la respuesta que nos da:

`resultado: {"Exito":false,"Mensaje":"El detalle de facturación es requerido"}`

Estoy utilizando el ejemplo que aparece en la documentacion con php, claro está haciendo los cambios como son: 

`$data->Email = "demo@ifactura.com.ar";
  $data->Password ="testing1";
  $ch = curl_init('https://demo.ifactura.com.ar/API/EmitirFactura');`

Que sugerencia me podrían hacer, para esperar la respuesta deseada  ?

Gracias

**Comment by sierraja** [comment]
Buenos días, por favor según el comentario anterior, me podrían corregir que estoy haciendo mal para que no responda estado true.

Gracias por su atención

**Comment by villaboamiguel** [comment]
El mensaje indica que no estas enviando un detalle de facturación a la API para ser procesador. Revisa el objeto que le estas enviando. El mensaje que te adjunta el sistema es lo que te falta o esta incompleto.

Saludos!

**Comment by sierraja** [comment]
Eso lo entiendo, estoy siguiendo el ejemplo, tal como aparece en la documentación, por eso me extraño, que no funcionan y me preguntaban cual sería el formato real que recibe su API, podrías verificar el ejemplo, tal vez no estoy viendo las cosas bien, solo hice un copia y paste y modifique datos de conexion y se envía pero solo dice el detalle de la factura es requerido, algo está mal en el ejemplo ?

Gracias por su atención

**Comment by villaboamiguel** [comment]
Fijate el $i en el ejemplo ponelo en 0
```
$i = 0;
```
El ejemplo es muy básico y te recomiendo implementar el código PHP en base a tus necesidades y requisitos de tu sistema.

**Comment by sierraja** [comment]
Gracias, eso trato de hacer, intento recrear el ejemplo de la documentación, debería funcionar, ya que está de ejemplo, a eso me refiero, por lo demás debemos hacer los ajustes.

Nuevamente gracias y disculpe las molestias
