### ISSUE TITLE
Comprobante B, parámetros correctos

### ISSUE THREAD

**Issue by sierraja** [wnpower/iFactura-API-Integracion#5]
Buenas tardes, tengo una duda acerca del comprobante que genera, en este caso ifactura (por ser plataforma demo), los montos que se muestran en el comprobante no coinciden, es decir, para el generar el comprobante Tipo B, se deben enviar los monto sin el IVA, es decir la base imponible y al procesar el comprobante se agrega el impuesto. Esto funciona así con los comprobantes Tipo B o estoy haciendo algo mal al momento de enviar la petición

**Comment by villaboamiguel** [comment]
Hola!
Comentame que información estas enviando y que información esperas ver.

Te muestro un pequeño ejemplo:
```js
{
	"Cantidad": 5,
	"ValorUnitario": 1016.00,
	"Total": 5080.00,
	"Descripcion": "CABLE UNIPOLAR 2.50MM CELESTE CAT. 5 EXTRAFLEXIBLE (100MTS) (Kalop)",
	"Codigo": "KS20042",
	"AlicuotaIVA": 3,
	"IVA": 1066.80,
	"UnidadMedida": 7,
	"Bonificacion": 0,
	"ConceptoFactura": 1
}
````
Siendo:
**ValorUnitario**: El valor unitario del producto sin IVA
**IVA**: Total de IVA al facturar.
**Total**: Total sin IVA e impuestos.
**AlicuotaIVA**: El ID 3 para que sea 21%

(Unitario * Cantidad) * (1 + (% IVA / 100)) = Total final
(1016.00 * 5) * (1 + (21 / 100)) = 6146,80
Yo espero ver una factura por un total de 6146,80

Te va a pasar que el valor unitario en una factura B en el PDF lo veas más grande, en este caso 1229,36 porque las facturas B no se discrimina IVA pero si se incluye.
Lo que ves es 1016 * 1.21

Espero que te sea claro.
Saludos!

**Comment by sierraja** [comment]
Excelente, aclaradaa la duda. Muchas Gracias
