### ISSUE TITLE
Implementando a producción

### ISSUE THREAD

**Issue by sierraja** [wnpower/iFactura-API-Integracion#6]
Buenas tardes, luego de hacer las pruebas en la plataforma de prueba, decidí pasar a la plataforma de producción, todos los cambios se hicieron bien, la aplicación se ejecutó perfecto, pero me está devolviendo un mensaje de PHP que es el siguiente:

`Creating default object from empty value in`

y sale justamente en la linea  donde creo: 

`$comprobante->DetalleFactura[$i]->Cantidad = $_POST['cantidad'];`

Aclaro, la factura me regresa estatus ok y su identificador, pero me devuelve tambien un creating default object from empty value in $comprobante->DetalleFactura[$i]->Cantidad = $_POST['cantidad'];

Que me sugieren para resolver, ese detalle. Gracias por su tiempo

**Comment by villaboamiguel** [comment]
Hola!
Eso es un warning de PHP. Te avisa que estas creando un objeto de la nada. No es algo grave pero es algo que se puede mejorar. Si queres evitarlo podrías hacer una clase en PHP que contenga las propiedades inicializadas. 

Por ejemplo en el caso del Detalle de la factura algo como
```php
class Comprobante
{
 private $DetalleFactura;
 function __construct()
    {
        $this->DetalleFactura = array();
    }

}
```
Es un ejemplo super simplificado, como el ejemplo que esta en la documentación, tenes que completarlo con las demás propiedades y el comportamiento que necesites implementar.

Saludos!

**Comment by sierraja** [comment]
Excelente, muchas gracias por su apoyo.
