### ISSUE TITLE
Error en WS

### ISSUE THREAD

**Issue by sierraja** [wnpower/iFactura-API-Integracion#7]
Buenos días.

Me está dando éste error, que puede estar pasando ?

`Error en WS: No se pudo obtener el ultimo comprobante emitido debido a problemas con los servicios de AFIP`

Gracias por su atención

**Comment by villaboamiguel** [comment]
Hola! 
Es tal cual dice el mensaje de error. En el momento que te conectaste con iFactura, la AFIP, tenia problemas en sus servicios online.

Como dato para futuro cualquier mensaje que diga **Error en COMPONENTE**, siendo en este caso WS el componente, indica que AFIP tiene problemas con sus servicios y deberias intentar más adelante.

Saludos.

**Comment by sierraja** [comment]
ok perfecto, gracias..!
