### ISSUE TITLE
Generar comprobante Tipo A

### ISSUE THREAD

**Issue by sierraja** [wnpower/iFactura-API-Integracion#8]
Buenas tardes, quisiera por favor me orientaran para emitir comprobantes de tipo A, es decir, cuales datos son obligatorios y los pasos a seguir. Ya estamos emitiendo comprobantes tipo B, ahora vamos por los comprobantes tipo A.

Gracias por su atención y tiempo.

**Comment by villaboamiguel** [comment]
Hola!
De la misma manera que la B, solo le tenes que cambiar el id de tipo de comprobante para el del tipo Factura A (1). Fijate también si tenes que ajustar algún valor de IVA.

También es importante recordar que el tipo de cliente que recibe comprobantes de tipo A es el responsable inscripto y que tiene un CUIT.

Saludos!

**Comment by sierraja** [comment]
ah ok perfecto, pero hay que enviar el CUIT ? o sólo se envía con el DNI, además como tu dices se cambia el ID de tipo de factura A en (1) y el envío es normal entonces ?

**Comment by villaboamiguel** [comment]
A un DNI no se le puede hacer una factura A. Si o si tiene que se a un CUIT de un responsable inscripto. Con cambiar el ID a factura A va a hacer una A.

Verifica que todos los datos estén correctos desde el punto de vista contable también. Si tenes dudas al respecto te recomiendo que consultes con un contador.

**Comment by sierraja** [comment]
Excelente, gracias por el apoyo
