### ISSUE TITLE
Error con WooCommerce

### ISSUE THREAD

**Issue by maxsarlija** [wnpower/iFactura-API-Integracion#9]
![error ifactura](https://user-images.githubusercontent.com/29083745/120046284-36583380-bfe8-11eb-99d7-86f191a6d0ba.jpg)
Tengo el siguiente error con WooCommerce, alguna idea?

**Comment by villaboamiguel** [comment]
Hola!
Este repositorio es de la API de iFactura, no tiene que ver con el plugin de woocommerce. Fijate acá: https://github.com/fedealvz/Woo-iFactura

Es más hay un issue al respecto con una recomendación para solucionar el asunto:
https://github.com/fedealvz/Woo-iFactura/issues/33

Saludos!
